/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,ts,tsx}", "./components/**/*.{js,ts,tsx}"],

  presets: [require("nativewind/preset")],
  theme: {
    colors: {
      primary: "#043222" /* Evergreen Shadow */,
      background: "#F6E9D9" /* Almond Cream */,
      accentGreen: "#6dbf9a" /* Sage Mint */,
      accentCta: "#c96b4a" /* Terracotta */,
    },
    extend: {
      fontFamily: {
        outfit: ["outfit-regular"],
        "outfit-medium": ["outfit-medium"],
        "outfit-semiBold": ["outfit-semiBold"],
        "outfit-bold": ["outfit-bold"],
        "outfit-extraBold": ["outfit-extraBold"],
        playfairDisplay: ["playfairDisplay-regular"],
        "playfairDisplay-medium": ["playfairDisplay-medium"],
        "playfairDisplay-semiBold": ["playfairDisplay-semiBold"],
        "playfairDisplay-bold": ["playfairDisplay-bold"],
        "playfairDisplay-extraBold": ["playfairDisplay-extraBold"],
        "playfairDisplay-italic": ["playfairDisplay-italic"],
      },
      spacing: {
        0: "0px",
        1: "4px",
        2: "8px",
        3: "12px",
        4: "16px",
        5: "20px",
        6: "24px",
        7: "28px",
        8: "32px",
        9: "36px",
        10: "40px",
        11: "44px",
        12: "48px",
        13: "52px",
        14: "56px",
        15: "60px",
        16: "64px",
        17: "68px",
        18: "72px",
        19: "76px",
        20: "80px",
        21: "84px",
        22: "88px",
        23: "92px",
        24: "96px",
        25: "100px",
        26: "104px",
        27: "108px",
        28: "112px",
        29: "116px",
        30: "120px",
      },
    },
  },
  plugins: [],
};
